### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Romz24** [OverlordsIII/VillagerNames#3] opened 2020-11-05 13:33 UTC
When trying to install a mod on a server, the server crashes.

Mod version: **1.16.3-1.2.2**
Minecraft version: **1.16.4**

File log: [latest.log](https://github.com/OverlordsIII/VillagerNames/files/5494693/latest.log)

**Comment by OverlordsIII** [comment] 2020-11-05 16:34
The problem is with the mod `VillagerFix` which overwrites parts of the vanilla code that VillagerNames tries to add on to. It is incompatible with this mod due to that. You will need to remove it to use this mod. Thanks for raising the report though, I will add it to the incompatible list for this mod

**Comment by OverlordsIII** [comment] 2020-11-05 16:47
Seems this is a crash with the mod `VillagerFix`. I think i can upload a fix for it by upping the priority.

**Comment by OverlordsIII** [comment] 2020-11-05 16:53
Ok I uploaded it on curseforge, try to get the latest release.

**Comment by OverlordsIII** [comment] 2020-12-14 20:37
I am going to go ahead and close this. If you get the latest release and the problem still happens, reopen this or message in this channel to reopen the issue

**Closed by OverlordsIII** 2020-12-14 20:37 UTC
Labels: bug
